# Use the official R base image
FROM rocker/r-ver:4.4.1

# Install necessary system dependencies for R packages and LaTeX in smaller batches
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libnetcdf-dev \
    netcdf-bin \
    libpng-dev \
    libfontconfig1-dev \
    libfreetype6-dev \
    texlive-latex-base \
    texlive-fonts-recommended && \
    apt-get clean && rm -rf /var/lib/apt/lists/*# Install necessary system dependencies for R packages

# Install remotes package to enable installation from GitHub
RUN R -e "install.packages('remotes', repos='https://cloud.r-project.org/')"
RUN R -e "install.packages('Seurat')"

# Copy the local GEMLI package directory to the Docker image and install the GEMLI package from the local directory
COPY GEMLI_package_v1 /opt/GEMLI_package_v1
RUN R -e "remotes::install_local('/opt/GEMLI_package_v1')"

# Install the GEMLI package from the specified subdirectory on GitHub
#RUN R -e "remotes::install_github('UPSUTER/GEMLI', subdir = 'GEMLI_package_v1')"

# Verify the installation
RUN R -e "library(GEMLI)"

# Set the command to R console
CMD ["R"]
